Modify flake to grab all wasm-pack related dependencies from the same nixpkgs it pulls the wasm-bindgen-cli from
Currently getting an error on chromium only in prod which I believe has
to do with this (different versions causing some linking issues or
something).

```
LinkError: WebAssembly.instantiate(): Import #213 "wbg" "__wbindgen_closure_wrapper1188": function import requires a callable
```